---
- hosts: 
    - switches
    - routers
  roles:
    - name: "role for switches"
      role: switch_api
      tags: switches
    - name: "role for routers"
      role: router_api
      tags: routers


